config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :bunkers do
      resources :bookings, only: [:new, :create]
      resources :reviews, only: [:new, :create]
    end
    resources :bookings, only: [:show, :edit, :update, :destroy]
      # member do
      #   patch :accepted
      #   patch :refused
      get 'dashboard', to: 'pages#dashboard'
      end
    # end
    # resources :pages
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bunker
  validates :nb_participants, :start_date, :end_date, presence: true
end

app/models/bunker.rb
class Bunker < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :bookings
  has_many :reviews
  has_one_attached :photo
  belongs_to :user
  has_one_attached :photo
  validates :name, :price, :description, :capacity, :address, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :bunker
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bunkers
  has_many :bookings
  has_many :reviews
  has_one_attached :photo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @booking = Booking.new
    @bunker = Bunker.find(params[:bunker_id])
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @bunker = Bunker.find(params[:bunker_id])
    @booking.bunker = @bunker
    @booking.user_id = current_user.id
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    if params[:status] == "Accept"
      @booking.update(status: "Accept")
    else
      @booking.update(status: "Refuse")
    end
  redirect_to dashboard_path
  end

  def accept
    booking = Booking.find(params[:id])
    booking.update_attribute(:status, "accepted")
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to booking_path
  end

  private

  def booking_params
    params.require(:booking).permit(:nb_participants, :start_date, :end_date, :total_price, :status)
  end
end

app/controllers/bunkers_controller.rb
class BunkersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @bunkers = policy_scope(Bunker).order(created_at: :desc)
    @markers = @bunkers.geocoded.map do |bunker|
      {
        lat: bunker.latitude,
        lng: bunker.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { bunker: bunker }),
      }
    end
  end

  def show
    @bunker = Bunker.find(params[:id])
    authorize @bunker
    @booking = Booking.new
  end

  def new
    @bunker = Bunker.new
    authorize @bunker
  end

  def edit
    @bunker = Bunker.find(params[:id])
  end

  def create
    @bunker = Bunker.new(bunker_params)
    authorize @bunker
    @bunker.user_id = current_user.id
    if @bunker.save
      redirect_to bunker_path(@bunker)
    else
      render :new
    end
  end

  def update
    @bunker = Bunker.find(params[:id])
    @bunker.update(bunker_params)
    redirect_to bunker_path(@bunker)
  end

  def destroy
    @bunker = Bunker.find(params[:id])
    @bunker.destroy
    redirect_to bunker_path
  end

  private

  def bunker_params
    params.require(:bunker).permit(:name, :price, :description, :capacity, :address, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    # Recuperer tous les bookings de l'utilisateur logged (locataire)
    @user = current_user
    # Recuperer les bunkers qui appartiennent aux users logged (proprio)
    @ownerbunkers = Bunker.where(user: @user)
    # Recuperer les demandes de bookings d'un autre utilisateur
    @bookings = Booking.where(bunker: @ownerbunkers)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @bunker = Bunker.find(params[:bunker_id])
  end

  def create
    @review = Review.new(review_params)
    @bunker = Bunker.find(params[:bunker_id])
    @review.bunker = @bunker
    if @review.save
      redirect_to review_path(@review)
    else
      render :new
    end
  end

  private

  def booking_params
    params.require (:booking).permit(:rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
edit.html.erb

app/views/bookings/new.html.erb
new.html.erb

app/views/bunkers/_info_window.html.erb
<h2><%= bunker.name %></h2>
<p><%= bunker.address %></p>
<p> <%= link_to "See more", bunker_path(bunker.id), class: "btn btn-flat pt-3" %> </p>

app/views/bunkers/edit.html.erb
edit.html.erb

app/views/bunkers/index.html.erb
<%= render "shared/search_form" %>

<div class="container sticky-top">
  <div
    id="map"
    style="width: 100%; height: 300px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>
<div class="container">
  <div class="cards mt-5">
    <% @bunkers.each do |bunker| %>
      <div class="card-category">
        <div class="card-trip">
         <% if bunker.photo.attached? %>
            <%= link_to bunker_path(bunker) do %>
             <%= cl_image_tag bunker.photo.key %>
            <% end %>
          <% end%>
          <div class="card-trip-infos">
            <div>
              <h2><%= bunker.name %></h2>
              <p><%= bunker.description %></p>
            </div>
            <h2 class="card-trip-pricing">€<%= bunker.price %></h2>
             <%= cl_image_tag bunker.user.photo.key, class: "card-trip-user avatar-bordered"%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bunkers/new.html.erb
<div class="container text-center mt-5">
  <h1> Add your bunker !!!</h1>
  <div class="form_size">
    <%= simple_form_for @bunker, input_html: { class: "form-inline"} do |f| %>
      <%= f.input :name, placeholder: "Name" %>
      <%= f.input :address, placeholder: "Address" %>
      <div class="flexbox-class">
        <%= f.input :price, placeholder: "Price" %>
        <%= f.input :capacity, placeholder: "Capacity" %>
      </div>
      <%= f.input :description,:as => :text, :input_html => {:rows => 6}, placeholder: "Description" %>
      <%= f.input :photo, input_html: {  class: 'd-none', id: 'photo-input'}, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>
      <%= f.button :submit, id: 'submit-button' %>
    <% end %>
  </div>
</div>

app/views/bunkers/show.html.erb
<div class="container">

  <div class="bunker-show">

      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%= cl_image_path @bunker.photo.key %>')">
        <div class="name">
          <h1> <%= @bunker.name %></h1>
        </div>
        <div class="tags">
          <h2> <%= @bunker.price %>€</h2>
          <p class="ml-4"> <%= @bunker.capacity %> <i class="fas fa-bed"></i> </p>
        </div>
      </div>

      <div class="details">

        <div class="description">
          <p class="text-center"><%= @bunker.description%><p>
          <p class="text-center"> <i class="fas fa-map-marked-alt"></i> <%= @bunker.address %></p>
        </div>

        <div class="booking_form">
          <div class="form">
            <%= simple_form_for [@bunker, @booking] do |f| %>
              <%= f.input :start_date, as: :string, input_html: { type: :date, class: 'recognitionStyling' }, placeholder: "" %>
              <%= f.input :end_date, as: :string, input_html: { type: :date, class: 'recognitionStyling' }, placeholder: "" %>
              <%= f.input :nb_participants, input_html: { class: 'recognitionStyling' }, placeholder: "1" %>
              <%= f.submit "Book now", class: 'btn' %>
            <% end %>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thebunker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashed' %>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <div class="cards-dashboard border-right border-secondary pr-5 mt-5">
        <h1> Booking Requests </h1>
        <% @bookings.each do |booking| %>
          <div class="card-category">
            <div class="card-trip">
             <% if booking.bunker.photo.attached? %>
                <%= link_to bunker_path(booking) do %>
                 <%= cl_image_tag booking.bunker.photo.key %>
                <% end %>
              <% end%>
              <div class="card-trip-infos">
                <div>
                  <h2><%= booking.bunker.name %></h2>
                  <p>Date:<%= booking.start_date %> - <%= booking.end_date %></p>
                  <% if booking.status == "pending" %>
                  <div class="mt-2">
                    <%= link_to "Accept", booking_path(booking, status: "Accept"), class: "btn-flat", method: :patch, data: { confirm: "Sure to accept ? "} %>
                    <%= link_to "Refuse", booking_path(booking, status: "Refuse"), class: "btn-flat-refuse", method: :patch, data: { confirm: "Sure to refuse ? "} %>
                  </div>
                  <% else %>
                  <p> <%= booking.status %></p>
                 <% end%>
                </div>
                <h2 class="card-trip-pricing">€<%= booking.bunker.price * (booking.end_date - booking.start_date).to_i %></h2>
               <%= cl_image_tag booking.bunker.user.photo.key, class: "card-trip-user avatar-bordered"%>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-6">
      <div class="cards-dashboard border-left border-secondary pl-5 mt-5">
        <h1> My Bookings </h1>
        <% @user.bookings.each do |booking| %>
          <div class="card-category">
            <div class="card-trip">
              <% if booking.bunker.photo.attached? %>
                <%= link_to bunker_path(booking.bunker) do %>
                 <%= cl_image_tag booking.bunker.photo.key %>
                <% end %>
              <% end%>
              <div class="card-trip-infos">
                <div>
                  <h2><%= booking.bunker.name %></h2>
                  <p><%= booking.bunker.description %></p>
                  <p>Status: <%= booking.status %></p>
                </div>
                  <h2 class="card-trip-pricing">€<%= booking.bunker.price * (booking.end_date - booking.start_date).to_i %></h2>
                  <%= cl_image_tag booking.bunker.user.photo.key, class: "card-trip-user avatar-bordered"%>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <hr>
  <br>
  <div class="row">
    <div class="col-12">
      <h1> My Bunkers </h1>
      <div class="cards mt-5">
        <% @ownerbunkers.each do |bunker| %>
          <div class="card-category">
            <div class="card-trip">
                <%= link_to wine_path(wine) do %>
                 <%= cl_image_tag bunker.photo.key %>
                <% end %>
              <% end%>
              <div class="card-trip-infos">
                <div>
                  <h2><%= bunker.name %></h2>
                  <p><%= bunker.description %></p>
                </div>
                <h2 class="card-trip-pricing">€<%= bunker.price %></h2>
                  <%= cl_image_tag bunker.user.photo.key, class: "card-trip-user avatar-bordered"%>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-banner">
  <%= render "shared/search_form" %>
    <div class="bannerpicture" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.home-designing.com/wp-content/uploads/2020/07/round-skylight.jpg);">
      <div class="container">
        <h1 class="a-primary">Checkout our Bunkers</h1>
        <br>
        <br>
        <p><span id="banner-typed-text"></span></p>
      </div>
    </div>
    <br>
    <div class="container">
      <h1 class="text-center">Bunker's of the month</h1>
      <div class="cards mt-5">
      <% Bunker.all.first(3).each do |bunker| %>
        <div class="card-category">
          <div class="card-trip">
            <%= link_to bunker_path(bunker) do %>
              <%= cl_image_tag bunker.photo.key %>
            <% end%>
            <div class="card-trip-infos">
              <div>
                <h2><%= bunker.name %></h2>
                <p><%= bunker.description %></p>
              </div>
              <h2 class="card-trip-pricing">€<%= bunker.price %></h2>
             <%= cl_image_tag bunker.user.photo.key, class: "card-trip-user avatar-bordered"%>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
new.html.erb

app/views/shared/_flashed.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Copyright © 2020 CheersTeam. All Rights Reserved
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "https://route66ventures.com/wp-content/uploads/2020/09/Bunker-Logo-1.png" %>
      <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <% if !user_signed_in?  %>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        <% end %>
      </li>
      <li>
        <% if user_signed_in?  %>
          <li> <%= link_to "Add my bunker", new_bunker_path, class: "nav-link mr-3" %> </li>
          <li> <%= link_to "Log out", destroy_user_session_path, :method => 'delete', class: "nav-link" %> </li>
            <li class="nav-item dropdown">
            <%= image_tag "https://avatars2.githubusercontent.com/u/69153626?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "My Dashboard", dashboard_path, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_search_form.html.erb
  <div class="search-form">
    <%= simple_form_for :search, url: bunkers_path, method: :get do |f| %>
      <div class="search-form-control form-group">
       <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="City" />
       <%= f.input :start_date, as: :string, required: false, label: false, input_html: {class: "datepicker"}, placeholder: "Start Date" %>
       <%= f.input :end_date, as: :string, required: false,label: false, input_html: {class: "datepicker"}, placeholder: "End Date" %>
       <button name="button" type="submit" class="btn btn-flat">
         <i class="fas fa-search"></i> Search
       </button>
      </div>
    <% end %>
  </div>